minimum_severity: CRITICAL
exclude:
  - aws-eks-no-public-cluster-access-to-cidr
  - aws-eks-no-public-cluster-access
# include:
#   - general-secrets-sensitive-in-attribute
#   - general-secrets-sensitive-in-attribute-value
#   - general-secrets-sensitive-in-local
#   - general-secrets-sensitive-in-variable
#   - general-secrets-no-plaintext-exposure
