name: "Terraform Destroy"

on: workflow_dispatch

env:
  TF_LOG: ERROR
  TF_INPUT: false
  TERRAFORM_VERSION: 1.6
  TF_IN_AUTOMATION: "True"
  AWS_REGION: us-west-2

jobs:
  terraform_destroy:
    name: "Destroy"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    defaults:
      run:
        shell: bash
        working-directory: terraform
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Configure GCP credentials
        id: gcp_auth
        uses: google-github-actions/auth@v2
        with:
          create_credentials_file: "true"
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - name: Terraform Init
        run: terraform init
      - name: Terraform destroy
        id: destroy
        run: terraform destroy -auto-approve
